// Auto-generated. Do not edit!

// (in-package omo_r1mini_simple_position_controller.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class VanillaPositionResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.x_result = null;
      this.y_result = null;
      this.theta_result = null;
    }
    else {
      if (initObj.hasOwnProperty('x_result')) {
        this.x_result = initObj.x_result
      }
      else {
        this.x_result = 0.0;
      }
      if (initObj.hasOwnProperty('y_result')) {
        this.y_result = initObj.y_result
      }
      else {
        this.y_result = 0.0;
      }
      if (initObj.hasOwnProperty('theta_result')) {
        this.theta_result = initObj.theta_result
      }
      else {
        this.theta_result = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type VanillaPositionResult
    // Serialize message field [x_result]
    bufferOffset = _serializer.float32(obj.x_result, buffer, bufferOffset);
    // Serialize message field [y_result]
    bufferOffset = _serializer.float32(obj.y_result, buffer, bufferOffset);
    // Serialize message field [theta_result]
    bufferOffset = _serializer.float32(obj.theta_result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type VanillaPositionResult
    let len;
    let data = new VanillaPositionResult(null);
    // Deserialize message field [x_result]
    data.x_result = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [y_result]
    data.y_result = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [theta_result]
    data.theta_result = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'omo_r1mini_simple_position_controller/VanillaPositionResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '43f67436b0054f56d2e5b2339aa76e1f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    float32 x_result
    float32 y_result
    float32 theta_result
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new VanillaPositionResult(null);
    if (msg.x_result !== undefined) {
      resolved.x_result = msg.x_result;
    }
    else {
      resolved.x_result = 0.0
    }

    if (msg.y_result !== undefined) {
      resolved.y_result = msg.y_result;
    }
    else {
      resolved.y_result = 0.0
    }

    if (msg.theta_result !== undefined) {
      resolved.theta_result = msg.theta_result;
    }
    else {
      resolved.theta_result = 0.0
    }

    return resolved;
    }
};

module.exports = VanillaPositionResult;
