// Auto-generated. Do not edit!

// (in-package omo_r1mini_simple_position_controller.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class VanillaPositionFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.error_s = null;
      this.error_theta = null;
    }
    else {
      if (initObj.hasOwnProperty('error_s')) {
        this.error_s = initObj.error_s
      }
      else {
        this.error_s = 0.0;
      }
      if (initObj.hasOwnProperty('error_theta')) {
        this.error_theta = initObj.error_theta
      }
      else {
        this.error_theta = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type VanillaPositionFeedback
    // Serialize message field [error_s]
    bufferOffset = _serializer.float32(obj.error_s, buffer, bufferOffset);
    // Serialize message field [error_theta]
    bufferOffset = _serializer.float32(obj.error_theta, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type VanillaPositionFeedback
    let len;
    let data = new VanillaPositionFeedback(null);
    // Deserialize message field [error_s]
    data.error_s = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [error_theta]
    data.error_theta = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'omo_r1mini_simple_position_controller/VanillaPositionFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'bebf2815c907dad92c117d5e622ce530';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #feedback
    float32 error_s
    float32 error_theta
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new VanillaPositionFeedback(null);
    if (msg.error_s !== undefined) {
      resolved.error_s = msg.error_s;
    }
    else {
      resolved.error_s = 0.0
    }

    if (msg.error_theta !== undefined) {
      resolved.error_theta = msg.error_theta;
    }
    else {
      resolved.error_theta = 0.0
    }

    return resolved;
    }
};

module.exports = VanillaPositionFeedback;
