(cl:defpackage omo_r1mini_simple_position_controller-msg
  (:use )
  (:export
   "<VANILLAPOSITIONACTION>"
   "VANILLAPOSITIONACTION"
   "<VANILLAPOSITIONACTIONFEEDBACK>"
   "VANILLAPOSITIONACTIONFEEDBACK"
   "<VANILLAPOSITIONACTIONGOAL>"
   "VANILLAPOSITIONACTIONGOAL"
   "<VANILLAPOSITIONACTIONRESULT>"
   "VANILLAPOSITIONACTIONRESULT"
   "<VANILLAPOSITIONFEEDBACK>"
   "VANILLAPOSITIONFEEDBACK"
   "<VANILLAPOSITIONGOAL>"
   "VANILLAPOSITIONGOAL"
   "<VANILLAPOSITIONRESULT>"
   "VANILLAPOSITIONRESULT"
  ))

