// Generated by gencpp from file omo_r1mini_bringup/CalgRequest.msg
// DO NOT EDIT!


#ifndef OMO_R1MINI_BRINGUP_MESSAGE_CALGREQUEST_H
#define OMO_R1MINI_BRINGUP_MESSAGE_CALGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace omo_r1mini_bringup
{
template <class ContainerAllocator>
struct CalgRequest_
{
  typedef CalgRequest_<ContainerAllocator> Type;

  CalgRequest_()
    {
    }
  CalgRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CalgRequest_

typedef ::omo_r1mini_bringup::CalgRequest_<std::allocator<void> > CalgRequest;

typedef boost::shared_ptr< ::omo_r1mini_bringup::CalgRequest > CalgRequestPtr;
typedef boost::shared_ptr< ::omo_r1mini_bringup::CalgRequest const> CalgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace omo_r1mini_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omo_r1mini_bringup/CalgRequest";
  }

  static const char* value(const ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::omo_r1mini_bringup::CalgRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OMO_R1MINI_BRINGUP_MESSAGE_CALGREQUEST_H
