// Generated by gencpp from file omo_r1mini_bringup/Calg.msg
// DO NOT EDIT!


#ifndef OMO_R1MINI_BRINGUP_MESSAGE_CALG_H
#define OMO_R1MINI_BRINGUP_MESSAGE_CALG_H

#include <ros/service_traits.h>


#include <omo_r1mini_bringup/CalgRequest.h>
#include <omo_r1mini_bringup/CalgResponse.h>


namespace omo_r1mini_bringup
{

struct Calg
{

typedef CalgRequest Request;
typedef CalgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Calg
} // namespace omo_r1mini_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::omo_r1mini_bringup::Calg > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::omo_r1mini_bringup::Calg&) { return value(); }
};

template<>
struct DataType< ::omo_r1mini_bringup::Calg > {
  static const char* value()
  {
    return "omo_r1mini_bringup/Calg";
  }

  static const char* value(const ::omo_r1mini_bringup::Calg&) { return value(); }
};


// service_traits::MD5Sum< ::omo_r1mini_bringup::CalgRequest> should match
// service_traits::MD5Sum< ::omo_r1mini_bringup::Calg >
template<>
struct MD5Sum< ::omo_r1mini_bringup::CalgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::omo_r1mini_bringup::Calg >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::CalgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::omo_r1mini_bringup::CalgRequest> should match
// service_traits::DataType< ::omo_r1mini_bringup::Calg >
template<>
struct DataType< ::omo_r1mini_bringup::CalgRequest>
{
  static const char* value()
  {
    return DataType< ::omo_r1mini_bringup::Calg >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::CalgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::omo_r1mini_bringup::CalgResponse> should match
// service_traits::MD5Sum< ::omo_r1mini_bringup::Calg >
template<>
struct MD5Sum< ::omo_r1mini_bringup::CalgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::omo_r1mini_bringup::Calg >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::CalgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::omo_r1mini_bringup::CalgResponse> should match
// service_traits::DataType< ::omo_r1mini_bringup::Calg >
template<>
struct DataType< ::omo_r1mini_bringup::CalgResponse>
{
  static const char* value()
  {
    return DataType< ::omo_r1mini_bringup::Calg >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::CalgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OMO_R1MINI_BRINGUP_MESSAGE_CALG_H
