// Generated by gencpp from file omo_r1mini_bringup/ResetOdom.msg
// DO NOT EDIT!


#ifndef OMO_R1MINI_BRINGUP_MESSAGE_RESETODOM_H
#define OMO_R1MINI_BRINGUP_MESSAGE_RESETODOM_H

#include <ros/service_traits.h>


#include <omo_r1mini_bringup/ResetOdomRequest.h>
#include <omo_r1mini_bringup/ResetOdomResponse.h>


namespace omo_r1mini_bringup
{

struct ResetOdom
{

typedef ResetOdomRequest Request;
typedef ResetOdomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResetOdom
} // namespace omo_r1mini_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::omo_r1mini_bringup::ResetOdom > {
  static const char* value()
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const ::omo_r1mini_bringup::ResetOdom&) { return value(); }
};

template<>
struct DataType< ::omo_r1mini_bringup::ResetOdom > {
  static const char* value()
  {
    return "omo_r1mini_bringup/ResetOdom";
  }

  static const char* value(const ::omo_r1mini_bringup::ResetOdom&) { return value(); }
};


// service_traits::MD5Sum< ::omo_r1mini_bringup::ResetOdomRequest> should match
// service_traits::MD5Sum< ::omo_r1mini_bringup::ResetOdom >
template<>
struct MD5Sum< ::omo_r1mini_bringup::ResetOdomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::omo_r1mini_bringup::ResetOdom >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::ResetOdomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::omo_r1mini_bringup::ResetOdomRequest> should match
// service_traits::DataType< ::omo_r1mini_bringup::ResetOdom >
template<>
struct DataType< ::omo_r1mini_bringup::ResetOdomRequest>
{
  static const char* value()
  {
    return DataType< ::omo_r1mini_bringup::ResetOdom >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::ResetOdomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::omo_r1mini_bringup::ResetOdomResponse> should match
// service_traits::MD5Sum< ::omo_r1mini_bringup::ResetOdom >
template<>
struct MD5Sum< ::omo_r1mini_bringup::ResetOdomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::omo_r1mini_bringup::ResetOdom >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::ResetOdomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::omo_r1mini_bringup::ResetOdomResponse> should match
// service_traits::DataType< ::omo_r1mini_bringup::ResetOdom >
template<>
struct DataType< ::omo_r1mini_bringup::ResetOdomResponse>
{
  static const char* value()
  {
    return DataType< ::omo_r1mini_bringup::ResetOdom >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::ResetOdomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OMO_R1MINI_BRINGUP_MESSAGE_RESETODOM_H
