// Generated by gencpp from file omo_r1mini_bringup/ResetOdomRequest.msg
// DO NOT EDIT!


#ifndef OMO_R1MINI_BRINGUP_MESSAGE_RESETODOMREQUEST_H
#define OMO_R1MINI_BRINGUP_MESSAGE_RESETODOMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace omo_r1mini_bringup
{
template <class ContainerAllocator>
struct ResetOdomRequest_
{
  typedef ResetOdomRequest_<ContainerAllocator> Type;

  ResetOdomRequest_()
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
    }
  ResetOdomRequest_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _theta_type;
  _theta_type theta;





  typedef boost::shared_ptr< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResetOdomRequest_

typedef ::omo_r1mini_bringup::ResetOdomRequest_<std::allocator<void> > ResetOdomRequest;

typedef boost::shared_ptr< ::omo_r1mini_bringup::ResetOdomRequest > ResetOdomRequestPtr;
typedef boost::shared_ptr< ::omo_r1mini_bringup::ResetOdomRequest const> ResetOdomRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator1> & lhs, const ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator1> & lhs, const ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace omo_r1mini_bringup

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "938fa65709584ad8e77d238529be13b8";
  }

  static const char* value(const ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x938fa65709584ad8ULL;
  static const uint64_t static_value2 = 0xe77d238529be13b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "omo_r1mini_bringup/ResetOdomRequest";
  }

  static const char* value(const ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResetOdomRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::omo_r1mini_bringup::ResetOdomRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "theta: ";
    Printer<double>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OMO_R1MINI_BRINGUP_MESSAGE_RESETODOMREQUEST_H
