// Generated by gencpp from file omo_r1mini_bringup/SaveColor.msg
// DO NOT EDIT!


#ifndef OMO_R1MINI_BRINGUP_MESSAGE_SAVECOLOR_H
#define OMO_R1MINI_BRINGUP_MESSAGE_SAVECOLOR_H

#include <ros/service_traits.h>


#include <omo_r1mini_bringup/SaveColorRequest.h>
#include <omo_r1mini_bringup/SaveColorResponse.h>


namespace omo_r1mini_bringup
{

struct SaveColor
{

typedef SaveColorRequest Request;
typedef SaveColorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveColor
} // namespace omo_r1mini_bringup


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::omo_r1mini_bringup::SaveColor > {
  static const char* value()
  {
    return "8b210d51c86d003e1192527182de7381";
  }

  static const char* value(const ::omo_r1mini_bringup::SaveColor&) { return value(); }
};

template<>
struct DataType< ::omo_r1mini_bringup::SaveColor > {
  static const char* value()
  {
    return "omo_r1mini_bringup/SaveColor";
  }

  static const char* value(const ::omo_r1mini_bringup::SaveColor&) { return value(); }
};


// service_traits::MD5Sum< ::omo_r1mini_bringup::SaveColorRequest> should match
// service_traits::MD5Sum< ::omo_r1mini_bringup::SaveColor >
template<>
struct MD5Sum< ::omo_r1mini_bringup::SaveColorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::omo_r1mini_bringup::SaveColor >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::SaveColorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::omo_r1mini_bringup::SaveColorRequest> should match
// service_traits::DataType< ::omo_r1mini_bringup::SaveColor >
template<>
struct DataType< ::omo_r1mini_bringup::SaveColorRequest>
{
  static const char* value()
  {
    return DataType< ::omo_r1mini_bringup::SaveColor >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::SaveColorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::omo_r1mini_bringup::SaveColorResponse> should match
// service_traits::MD5Sum< ::omo_r1mini_bringup::SaveColor >
template<>
struct MD5Sum< ::omo_r1mini_bringup::SaveColorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::omo_r1mini_bringup::SaveColor >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::SaveColorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::omo_r1mini_bringup::SaveColorResponse> should match
// service_traits::DataType< ::omo_r1mini_bringup::SaveColor >
template<>
struct DataType< ::omo_r1mini_bringup::SaveColorResponse>
{
  static const char* value()
  {
    return DataType< ::omo_r1mini_bringup::SaveColor >::value();
  }
  static const char* value(const ::omo_r1mini_bringup::SaveColorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OMO_R1MINI_BRINGUP_MESSAGE_SAVECOLOR_H
